# Site settings
title: CryptoMental
email: cryptomental.com@gmail.com.com
description: "We are CryptoMental"
info: "Visit steemit.com/@cryptomental"
message: "Where the blockchain meets innovation"
keywords: "steem,blockchain,development,opensource"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cryptomental.com" # the base hostname & protocol for your site
twitter_username: cryptomental.com
# Build settings
markdown: kramdown
author:
    name: Cryptomental
    twitter: cryptomental.com
    url: http://www.cryptomental.com
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: cryptomental.com at gmail.com
facebook:
    image: /images/delightfuldev-facebook-cover.png
